root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/strict
  - plugin:storybook/recommended
  - standard-with-typescript
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
    - ./tsconfig.node.json
plugins:
  - react-refresh
  - react
  - jsx-a11y
  - prettier
rules:
  "@typescript-eslint/strict-boolean-expressions": "off"
  react/hook-use-state:
    - 1
    - allowDestructuredState: true
  react-refresh/only-export-components:
    - 1
    - allowConstantExport: true
  prettier/prettier: error
settings:
  react:
    version: detect
